sudo: required
before_install:
- sudo apt-get install tomcat7
before_script:
- mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');"
- nvm ls
- nvm install node
- nvm use node
- npm -v
- node -v
- env
- npm install -g @angular/cli@latest
- npm install -g bower
- npm install @angular/core@latest
- chmod +x ./get_seroUtils.sh
- "./get_seroUtils.sh"
- ls -l ./WebContent/WEB-INF/lib/seroUtils.jar
- cd ./WebContent/resources/app; bower update;
- cd ../../..
- cd ./ScadaLTS-UI
- npm install
- ls -l ./src/app/media
- ng version
- ng build
- cd ./war
- ant war
- ant 
- cd ../..
language: java
jdk:
- openjdk8
services:
- docker
- mysql
script: ant war && ant junit
#script: ant war
branches:
  only:
  - "/^PROC-.*$/"
  - "/^develop-sdtabilit.*$/"
  - "/^#179*$/"
  - "/^master-sdtabilit.*$/"
  - "/^v*$/"
  - "/^develop*$/"
  - "/^master*$/"
notifications:
  email: false
env:
  matrix:
  - CATALINA_HOME=/usr/share/tomcat7
after_script:
# get tomcat7 to ./docker/app
- wget https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.85/bin/apache-tomcat-7.0.85.tar.gz
- mkdir ./docker/app
- mv apache-tomcat-7.0.85.tar.gz ./docker/app
- ls -l ./docker/app/apache-tomcat-7.0.85.tar.gz
- cd ./docker/app
- echo `pwd`
- echo `ls -l`
- tar -zxvf apache-tomcat-7.0.85.tar.gz
- ls -l
- mv ./apache-tomcat-7.0.85/* ./
- rm -rf ./apache-tomcat-7.0.85
- cp ../../ScadaBR.war ./webapps
- cp ../../ScadaLTS-UI/war/ScadaLTS.war ./webapps
- ls -l ./webapps/ScadaLTS.war
- ls -l ./webapps/ScadaBR.war
- cp ../../WebContent/WEB-INF/lib/mysql-connector-java-3.1.8-bin.jar ./lib/
- cp ../../WebContent/WEB-INF/lib/mysql-connector-java-5.1.38-bin.jar ./lib/
- ls -l ./lib/mysql-connector-java-3.1.8-bin.jar
- ls -l ./lib/mysql-connector-java-5.1.38-bin.jar
# config tomcat
- cp -f ../config/context.xml ./conf/
- cat ./conf/context.xml

# docker
- cd ../
- pwd
- ls 
- docker version
- docker build -t quay.io/loopedge/scadalts .
- docker images
- docker login -u=$DOCKER_USENAME -p=$DOCKER_PASSWORD
- docker push quay.io/loopedge/scadalts 

#- echo $TRAVIS_BUILD_DIR
